### ISSUE TITLE
1.13

### ISSUE THREAD

**Issue by MarcinWieczorek** [badbones69/Block-Particles#12]
Are you working on an 1.13 update?

**Comment by MarcinWieczorek** [comment]
Also, why won't you use Bukkit's particle API?

**Comment by smmmadden** [comment]
looks like it isn't working on 1.13.  I tried setting a location and it failed big time with about 35,000 lines of exceptions repeating in the console. :-)  So I guess it isn't quite ready yet.
![image](https://user-images.githubusercontent.com/10309346/44245466-c665bf00-a1a6-11e8-992d-bba5d3af04cc.png)

**Comment by MarcinWieczorek** [comment]
Yeah because the API has changed.

**Comment by lolita-is-godddd** [comment]
why not modify with lambda or something can delay (means doesn't error even if call non-exist the version)

**Comment by MarcinWieczorek** [comment]
A try-catch is enough, but it's better not to use workarounds but to find solutions.

**Comment by imflitch** [comment]
Any update on this version 1.13?
