### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by 21stCheran** [badbones69/Block-Particles#15]
20.10 04:30:36 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:36 [Server] INFO at me.badbones69.blockparticles.PlayParticles$5.run(PlayParticles.java:164) ~[?:?]
20.10 04:30:36 [Server] INFO at me.badbones69.blockparticles.Methods.anyPlayers(Methods.java:65) ~[?:?]
20.10 04:30:36 [Server] INFO at me.badbones69.blockparticles.Methods.getNearbyEntities(Methods.java:48) ~[?:?]
20.10 04:30:36 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.World.spawnFallingBlock(Lorg/bukkit/Location;IB)Lorg/bukkit/entity/FallingBlock;
20.10 04:30:36 [Server] INFO [04:30:36 WARN]: [BlockParticles] Task #11 for BlockParticles v1.9.7.2 generated an exception
20.10 04:30:36 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
20.10 04:30:36 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:36 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:36 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:36 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:36 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:36 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:36 [Server] INFO at me.badbones69.blockparticles.PlayParticles$32.run(PlayParticles.java:741) ~[?:?]
20.10 04:30:36 [Server] INFO at me.badbones69.blockparticles.Methods.anyPlayers(Methods.java:65) ~[?:?]
20.10 04:30:36 [Server] INFO at me.badbones69.blockparticles.Methods.getNearbyEntities(Methods.java:48) ~[?:?]
20.10 04:30:36 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.World.spawnFallingBlock(Lorg/bukkit/Location;IB)Lorg/bukkit/entity/FallingBlock;
20.10 04:30:36 [Server] INFO [04:30:36 WARN]: [BlockParticles] Task #10 for BlockParticles v1.9.7.2 generated an exception
20.10 04:30:36 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
20.10 04:30:36 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:36 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:36 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:36 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:36 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:36 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:36 [Server] INFO at me.badbones69.blockparticles.PlayParticles$5.run(PlayParticles.java:164) ~[?:?]
20.10 04:30:36 [Server] INFO at me.badbones69.blockparticles.Methods.anyPlayers(Methods.java:65) ~[?:?]
20.10 04:30:36 [Server] INFO at me.badbones69.blockparticles.Methods.getNearbyEntities(Methods.java:48) ~[?:?]
20.10 04:30:36 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.World.spawnFallingBlock(Lorg/bukkit/Location;IB)Lorg/bukkit/entity/FallingBlock;
20.10 04:30:36 [Server] INFO [04:30:36 WARN]: [BlockParticles] Task #11 for BlockParticles v1.9.7.2 generated an exception
20.10 04:30:36 [Multicraft] Skipped 162 lines due to rate limit (30/s)
20.10 04:30:35 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:35 [Server] INFO at me.badbones69.blockparticles.PlayParticles$5.run(PlayParticles.java:164) ~[?:?]
20.10 04:30:35 [Server] INFO at me.badbones69.blockparticles.Methods.anyPlayers(Methods.java:65) ~[?:?]
20.10 04:30:35 [Server] INFO at me.badbones69.blockparticles.Methods.getNearbyEntities(Methods.java:48) ~[?:?]
20.10 04:30:35 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.World.spawnFallingBlock(Lorg/bukkit/Location;IB)Lorg/bukkit/entity/FallingBlock;
20.10 04:30:35 [Server] INFO [04:30:35 WARN]: [BlockParticles] Task #11 for BlockParticles v1.9.7.2 generated an exception
20.10 04:30:35 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
20.10 04:30:35 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:35 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:35 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:35 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:35 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:35 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:35 [Server] INFO at me.badbones69.blockparticles.PlayParticles$5.run(PlayParticles.java:164) ~[?:?]
20.10 04:30:35 [Server] INFO at me.badbones69.blockparticles.Methods.anyPlayers(Methods.java:65) ~[?:?]
20.10 04:30:35 [Server] INFO at me.badbones69.blockparticles.Methods.getNearbyEntities(Methods.java:48) ~[?:?]
20.10 04:30:35 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.World.spawnFallingBlock(Lorg/bukkit/Location;IB)Lorg/bukkit/entity/FallingBlock;
20.10 04:30:35 [Server] INFO [04:30:35 WARN]: [BlockParticles] Task #11 for BlockParticles v1.9.7.2 generated an exception
20.10 04:30:35 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
20.10 04:30:35 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:35 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:35 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:35 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:35 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:35 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:35 [Server] INFO at me.badbones69.blockparticles.PlayParticles$3.run(PlayParticles.java:76) ~[?:?]
20.10 04:30:35 [Server] INFO at me.badbones69.blockparticles.Methods.anyPlayers(Methods.java:65) ~[?:?]
20.10 04:30:35 [Server] INFO at me.badbones69.blockparticles.Methods.getNearbyEntities(Methods.java:48) ~[?:?]
20.10 04:30:35 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.World.spawnFallingBlock(Lorg/bukkit/Location;IB)Lorg/bukkit/entity/FallingBlock;
20.10 04:30:35 [Server] INFO [04:30:35 WARN]: [BlockParticles] Task #9 for BlockParticles v1.9.7.2 generated an exception
20.10 04:30:35 [Multicraft] Skipped 150 lines due to rate limit (30/s)
20.10 04:30:34 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:34 [Server] INFO at me.badbones69.blockparticles.PlayParticles$5.run(PlayParticles.java:164) ~[?:?]
20.10 04:30:34 [Server] INFO at me.badbones69.blockparticles.Methods.anyPlayers(Methods.java:65) ~[?:?]
20.10 04:30:34 [Server] INFO at me.badbones69.blockparticles.Methods.getNearbyEntities(Methods.java:48) ~[?:?]
20.10 04:30:34 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.World.spawnFallingBlock(Lorg/bukkit/Location;IB)Lorg/bukkit/entity/FallingBlock;
20.10 04:30:34 [Server] INFO [04:30:34 WARN]: [BlockParticles] Task #11 for BlockParticles v1.9.7.2 generated an exception
20.10 04:30:34 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
20.10 04:30:34 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:34 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:34 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:34 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:34 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:34 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:34 [Server] INFO at me.badbones69.blockparticles.PlayParticles$5.run(PlayParticles.java:164) ~[?:?]
20.10 04:30:34 [Server] INFO at me.badbones69.blockparticles.Methods.anyPlayers(Methods.java:65) ~[?:?]
20.10 04:30:34 [Server] INFO at me.badbones69.blockparticles.Methods.getNearbyEntities(Methods.java:48) ~[?:?]
20.10 04:30:34 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.World.spawnFallingBlock(Lorg/bukkit/Location;IB)Lorg/bukkit/entity/FallingBlock;
20.10 04:30:34 [Server] INFO [04:30:34 WARN]: [BlockParticles] Task #11 for BlockParticles v1.9.7.2 generated an exception
20.10 04:30:34 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
20.10 04:30:34 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:34 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:34 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:34 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:34 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:34 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:34 [Server] INFO at me.badbones69.blockparticles.PlayParticles$3.run(PlayParticles.java:76) ~[?:?]
20.10 04:30:34 [Server] INFO at me.badbones69.blockparticles.Methods.anyPlayers(Methods.java:65) ~[?:?]
20.10 04:30:34 [Server] INFO at me.badbones69.blockparticles.Methods.getNearbyEntities(Methods.java:48) ~[?:?]
20.10 04:30:34 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.World.spawnFallingBlock(Lorg/bukkit/Location;IB)Lorg/bukkit/entity/FallingBlock;
20.10 04:30:34 [Server] INFO [04:30:34 WARN]: [BlockParticles] Task #9 for BlockParticles v1.9.7.2 generated an exception
20.10 04:30:34 [Multicraft] Skipped 174 lines due to rate limit (30/s)
20.10 04:30:33 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:33 [Server] INFO at me.badbones69.blockparticles.PlayParticles$3.run(PlayParticles.java:76) ~[?:?]
20.10 04:30:33 [Server] INFO at me.badbones69.blockparticles.Methods.anyPlayers(Methods.java:65) ~[?:?]
20.10 04:30:33 [Server] INFO at me.badbones69.blockparticles.Methods.getNearbyEntities(Methods.java:48) ~[?:?]
20.10 04:30:33 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.World.spawnFallingBlock(Lorg/bukkit/Location;IB)Lorg/bukkit/entity/FallingBlock;
20.10 04:30:33 [Server] INFO [04:30:33 WARN]: [BlockParticles] Task #9 for BlockParticles v1.9.7.2 generated an exception
20.10 04:30:33 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
20.10 04:30:33 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:33 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:33 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:33 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:33 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:33 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:33 [Server] INFO at me.badbones69.blockparticles.PlayParticles$5.run(PlayParticles.java:164) ~[?:?]
20.10 04:30:33 [Server] INFO at me.badbones69.blockparticles.Methods.anyPlayers(Methods.java:65) ~[?:?]
20.10 04:30:33 [Server] INFO at me.badbones69.blockparticles.Methods.getNearbyEntities(Methods.java:48) ~[?:?]
20.10 04:30:33 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.World.spawnFallingBlock(Lorg/bukkit/Location;IB)Lorg/bukkit/entity/FallingBlock;
20.10 04:30:33 [Server] INFO [04:30:33 WARN]: [BlockParticles] Task #11 for BlockParticles v1.9.7.2 generated an exception
20.10 04:30:33 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
20.10 04:30:33 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:33 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:33 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:434) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:33 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:33 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:33 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[PaperSpigot-1.13.1-b351.jar:git-Paper-351]
20.10 04:30:33 [Server] INFO at me.badbones69.blockparticles.PlayParticles$32.run(PlayParticles.java:741) ~[?:?]
20.10 04:30:33 [Server] INFO at me.badbones69.blockparticles.Methods.anyPlayers(Methods.java:65) ~[?:?]

I get spammed by this all the time on the console.

**Comment by weeryan17** [comment]
It appears this plugin doesn't support 1.13 yet. I suggest you refer to issue #12
