### ISSUE TITLE
no particle showing spigot 1.12

### ISSUE THREAD

**Issue by juliu123** [badbones69/Block-Particles#9]
Hi Kicjow when i type "/bp set test spiral" there's no particle showing except for halo and all fountain particles., But there is no error showing in console just the particle is not showing.
There's maybe a dependency  in this plugin? or is there i can do or you can do here?
this is cool and helpful plugin for my server and other servers.

**Comment by kicjow** [comment]
Sorry for the very late response, make sure your particles are turned on in your settings.
